CMD: 'bash /myws/codes/ngc_comm/install.sh; python boostrap.py'

HPARAMS:
  resume: [0]
  batch_size: [256]
  epoch: [100]
  lr: [0.01]
  subset_pct: [0.1]
  di_batch_size: [1024]
  num_di_batch: [6]
  di_milestone: ['10000', '30', '50', '70', '50,70']
  logdir: LOGDIR

