CMD: 'bash /myws/codes/ngc_comm/install.sh;python boostrap.py'

HPARAMS:
  batch_size: [256]
  epoch: [100]
  lr: [0.01]
  subset_pct: [0.1, 0.5]
  di_batch_size: [256]
  num_di_batch: [200]
  logdir: LOGDIR

gdir: LOGDIR

